# Generated by Django 4.1.2 on 2022-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_project_employee_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(default='2022-10-01'),
            preserve_default=False,
        ),
    ]
